INSERT INTO tender_intelligence_sources (
  source_key,
  track,
  source_type,
  source_name,
  source_url,
  collection_method,
  verification_level,
  coverage_scope,
  coverage_state_name,
  priority_order,
  refresh_interval_minutes,
  is_active,
  notes
)
VALUES
  (
    'CPPP_EPROCURE',
    'government',
    'government_tender',
    'Central Public Procurement Portal (CPPP / eProcure)',
    'https://eprocure.gov.in/eprocure/app',
    'html',
    'OFFICIAL_PORTAL',
    'national',
    NULL,
    10,
    60,
    TRUE,
    'Primary national government tender backbone for phase 1.'
  ),
  (
    'GEM_BIDS',
    'government',
    'government_tender',
    'Government e Marketplace (GeM) Bids',
    'https://gem.gov.in/',
    'html',
    'OFFICIAL_PORTAL',
    'national',
    NULL,
    20,
    60,
    TRUE,
    'Separate government tender stream; keep trust labeling aligned with official GeM pages.'
  ),
  (
    'KARNATAKA_KPPP',
    'government',
    'government_tender',
    'Karnataka Public Procurement Portal (KPPP)',
    'https://kppp.karnataka.gov.in/',
    'html',
    'OFFICIAL_PORTAL',
    'state',
    'Karnataka',
    30,
    60,
    TRUE,
    'State procurement backbone for Karnataka-first rollout.'
  ),
  (
    'PIB_INFRA',
    'government',
    'government_notice',
    'Press Information Bureau Infrastructure Announcements',
    'https://pib.gov.in/',
    'rss',
    'PUBLIC_NOTICE_PRESS_RELEASE',
    'national',
    NULL,
    40,
    180,
    TRUE,
    'Used for official announcements, approvals, and press-release style updates.'
  ),
  (
    'LGD_DIRECTORY',
    'government',
    'village_signal',
    'Local Government Directory (LGD)',
    'https://lgdirectory.gov.in/',
    'hybrid',
    'OFFICIAL_DEPARTMENT_SITE',
    'national',
    NULL,
    50,
    1440,
    TRUE,
    'Location normalization backbone for state, district, block, and village codes.'
  ),
  (
    'KARNATAKA_DEPT_TENDERS',
    'government',
    'government_tender',
    'Karnataka Department Tender Pages',
    'https://www.karnataka.gov.in/',
    'html',
    'OFFICIAL_DEPARTMENT_SITE',
    'state',
    'Karnataka',
    60,
    360,
    TRUE,
    'Use after CPPP and KPPP coverage is stable.'
  ),
  (
    'KARNATAKA_LOCAL_BODIES',
    'government',
    'government_notice',
    'Karnataka District and Local Body Websites',
    'https://www.karnataka.gov.in/english',
    'html',
    'OFFICIAL_DEPARTMENT_SITE',
    'district',
    'Karnataka',
    70,
    1440,
    TRUE,
    'Lower-frequency crawl tier for district and local-government updates.'
  ),
  (
    'PRIVATE_MARKET_PORTALS',
    'private',
    'private_opportunity',
    'Private Tender and Market Opportunity Portals',
    'https://www.tenderdetail.com/',
    'html',
    'MARKET_SOURCE',
    'private_network',
    NULL,
    80,
    720,
    FALSE,
    'Keep private opportunities separated from government trust badges until the module is enabled.'
  ),
  (
    'INFRA_LEGACY_PUBLIC',
    'government',
    'government_notice',
    'Legacy Public Infrastructure Feed',
    'https://example.invalid/legacy-public-feed',
    'manual',
    'OFFICIAL_DEPARTMENT_SITE',
    'national',
    NULL,
    500,
    60,
    TRUE,
    'Fallback registry entry for existing infra_updates rows until a more specific source is known.'
  )
ON CONFLICT (source_key)
DO UPDATE
  SET track = EXCLUDED.track,
      source_type = EXCLUDED.source_type,
      source_name = EXCLUDED.source_name,
      source_url = EXCLUDED.source_url,
      collection_method = EXCLUDED.collection_method,
      verification_level = EXCLUDED.verification_level,
      coverage_scope = EXCLUDED.coverage_scope,
      coverage_state_name = EXCLUDED.coverage_state_name,
      priority_order = EXCLUDED.priority_order,
      refresh_interval_minutes = EXCLUDED.refresh_interval_minutes,
      is_active = EXCLUDED.is_active,
      notes = EXCLUDED.notes,
      updated_at = NOW();
